version: '3.8'

networks: 
    kinder:

services:
    service-nginx:
        image: nginx:stable-alpine
        container_name: kinder-nginx
        networks:
            - kinder
        ports:
            - "8000:80"
        volumes:
            - ./app/public:/var/app/public
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - service-php74
            - service-postgres

    service-php74:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: kinder-php74
        networks:
            - kinder
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/app/

    service-postgres:
        image: postgres:13-alpine
        container_name: kinder-postgres
        networks:
            - kinder
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/var/lib/postgres/data
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: kinder

    service-node-js:
        image: node:latest
        container_name: kinder-node
        working_dir: /var/app
        networks:
            - kinder
        volumes: 
            - ./app:/var/app

